BitcoinFixesThis_771180
ventunobtc/video-youtube pull request #5
Opened 2023-01-09 22:49 UTC by andreatheorange

markdown file del video _Bitcoin Fixes This_ 
- trascrizione inglese
- trascrizione italiana

aggiornamento ReadMe principale

2023-01-18 09:00 UTC, cyphersats requested changes

2023-01-21 08:08 UTC, andreatheorange commented on BitcoinFixesThis/ch001-bitcoin-risolve-questo-problema.md
> +<br/>Bitcoin è molte cose in una: è l'evoluzione dell'oro, la precedente miglior moneta che il mondo abbia mai visto, e la rivoluzione delle valute fiat.
Come mai?
Se cancellassi il corrispettivo di _previously_ (_precedente_), avremmo
"Bitcoin è molte cose in una: è l'evoluzione dell'oro, la miglior moneta che il mondo abbia mai visto, e la rivoluzione delle valute fiat."

Questo andrebbe bene se "la miglior moneta che il mondo abbia mai visto" si riferisse a Bitcoin, ma secondo me si riferisce all'oro, di cui Bitcoin è l'evoluzione.

2023-01-24 06:23 UTC, cyphersats commented on BitcoinFixesThis/ch001-bitcoin-risolve-questo-problema.md
> +<br/>Bitcoin è molte cose in una: è l'evoluzione dell'oro, la precedente miglior moneta che il mondo abbia mai visto, e la rivoluzione delle valute fiat.
Hai ragione. Io mi riferivo a Bitcoin erroneamente.

2023-01-24 06:29 UTC, cyphersats approved these changes

2023-05-15 01:45 UTC, merged