Ross Ulbricht @Miami Bitcoin Conference
ventunobtc/video-youtube pull request #6
Opened 2023-01-10 18:47 UTC by Cmod777

2023-01-10 19:31 UTC, Cmod777 commented
Modificato errore link da tabella a traduzione IT

2023-01-24 07:30 UTC, cyphersats requested changes
Per la trascrizione in inglese:
- inserire le lettere maiuscole quando necessarie (es: Bitcoin, I e Silk Road)
- rivedere la punteggiatura
- riascoltare per capire se ci sono dimenticanze o errori

2023-01-24 07:30 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/en/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> + Ross Robinson.
Modificare in:" And she said to me in this voice, she said:"oh Ross,  
 Ross Ross" "

2023-01-24 07:30 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/en/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> + The are mothers and fathers.
Correzione:"There"

2023-02-04 01:29 UTC, cyphersats requested changes

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  Ora cominci a capire cosa significa 
Correggere `Ora cominci a capire` con `Ora cominciate a capire`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  È una vita che è stata accuratamente costruita per giustificare 
Correggere `È una vita che è stata` con `È una bugia viva, che è stata`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  La caricatura che hanno creato è quella di un violento signore della droga. 
Correggere `violento signore della droga` con `violento detentore di droga`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> + Mi piaceva molto, 
Correggere con `Mi piaceva così tanto`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  Allora ero entusiasta, 
Correggere con `All'epoca ero entusiasta`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  ma ero anche molto impaziente. 
Correggere con `ma anche molto impaziente`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  State facendo quello che io non ho avuto la pazienza di fare. 
Correggere `la pazienza di fare` con `la pazienza di fare per questi ultimi otto anni in prigione.`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  Più volte sono rimasto così 
Correggere `Più volte` con `Più e più volte`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  Ha molti nomi: la segregazione, 
Correggere con `Ha molti nomi: le scarpe, la segregazione,`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  Voglio che tu capisca cosa 
Correggere `che tu capisca` con `che voi capiate`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  qualcuno ti ha già parlato di mamma? 
Correggere con `"Qualcuno ti ha già parlato di mamma?" E io: "cosa?"`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  E lei mi ha risposto e ha detto: "Oh Ross"...
Correggere `"Oh Ross"...` con `"Oh Ross, Ross, Ross..."`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  Quando correvo quei rischi, 
Correggere `non quanto avrei dovuto. Quando correvo quei rischi` con `non quanto avrei dovuto quando correvo quei rischi`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  -
Inserire `Ero ingobbito come una specie di obiettivo`

2023-02-04 01:29 UTC, cyphersats commented on Ross-Ulbricht-Miami-Bitcoin-Conference/It/ch001-Ross-Ulbricht-Miami-Bitcoin-Conference.md
> +  mi ha dato la speranza che tu non mi guardassi come se fossi una specie di mostro. 
Correggere `che tu non mi guardassi` con `che voi non mi guardaste`

2023-05-18 18:44 UTC, merged